language: php

php:
  - '7.1'
  - '7.2'
  - 'nightly'

git:
  depth: false
  submodules: false

before_install:
  - stty cols 120
  - phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
  
install:
  - composer update
  
script:
  - vendor/bin/php-cs-fixer --dry-run --diff -v fix 
