language: php
php:
  - '7.1'
  - '7.2'
  - 'nightly'

before_install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  
install:
  - composer install
  
script:
  - vendor/bin/php-cs-fixer --dry-run --diff -v fix 
